#182282571: Start django app - users
Skaehub-Technologies/convint-sky-bend pull request #12
Opened 2022-06-13 08:05 UTC by narravabrion

#### What does this Pull Request do?
+ start a user app

#### Description of Task to be completed?
+ start user app
+ create custom user model
+ register model to admin panel

#### How should this be manually tested?
+ unittests for models

#### Any background context you want to provide?
N/A

#### What are the relevant Pivotal tracker card?
+ Start django app - users
#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2022-06-13 09:53 UTC, MwanikiN commented on requirements.txt
> -mypy==0.812
mypy==0.961. Latest version.

2022-06-13 09:53 UTC, MwanikiN commented on requirements.txt
> -psycopg2-binary
psycopg2--binary   Corrected a missing (-)

2022-06-13 15:38 UTC, mainamuriuki274 requested changes

2022-06-13 15:38 UTC, mainamuriuki274 commented on core/settings/base.py
> +AUTH_USER_MODEL = 'users.User'
add an emplty line after this file

2022-06-13 15:38 UTC, mainamuriuki274 commented on users/admin.py
> +# Register your models here.
remove this line

2022-06-13 15:38 UTC, mainamuriuki274 commented on users/admin.py
> +admin.site.register(User)
add an empty line after this line

2022-06-13 15:38 UTC, mainamuriuki274 commented on users/models.py
> +# Create your models here.
remove this linne

2022-06-15 07:03 UTC, narravabrion commented on requirements.txt
> -mypy==0.812
Use mypy==0.950

2022-06-15 07:12 UTC, narravabrion commented on core/settings/base.py
> +AUTH_USER_MODEL = 'users.User'
done

2022-06-15 07:13 UTC, narravabrion commented on users/admin.py
> +# Register your models here.
done

2022-06-15 07:13 UTC, narravabrion commented on users/admin.py
> +admin.site.register(User)
done

2022-06-15 07:13 UTC, narravabrion commented on users/models.py
> +# Create your models here.
done

2022-06-15 07:27 UTC, mainamuriuki274 requested changes

2022-06-15 07:27 UTC, mainamuriuki274 commented on users/models.py
> +class Profile(models.Model):
create an abstract TimeStampedModel that is inherited in all models

2022-06-15 07:27 UTC, mainamuriuki274 commented on users/models.py
> +class User(AbstractBaseUser, PermissionsMixin):
create an abstract TimeStampedModel that is inherited in all models

2022-06-15 07:27 UTC, mainamuriuki274 commented on users/models.py
> +        user.save(using=self._db)
you can remove using=self._db

2022-06-15 07:27 UTC, mainamuriuki274 commented on users/models.py
> +        user.save(using=self._db)
you can remove using=self._db

2022-06-15 07:27 UTC, mainamuriuki274 commented on users/models.py
> +        user.save(using=self._db)
you can remove using=self._db

2022-06-15 07:27 UTC, mainamuriuki274 commented on .vscode/settings.json
> +    "python.formatting.provider": "black"
add .vscode to .gitignore

2022-06-15 09:57 UTC, mainamuriuki274 requested changes

2022-06-15 09:57 UTC, mainamuriuki274 commented on .vscode/settings.json
> +}
You need to delete this file also

2022-06-15 09:57 UTC, mainamuriuki274 commented on users/models.py
> +class Profile(TimeStampedModel, models.Model):
if you've inherited TimeStampedModel , you do not need to inherit models.Model

2022-06-15 10:15 UTC, mainamuriuki274 approved these changes

2022-06-15 10:17 UTC, merged